# pytorch 인덱싱과 슬라이싱

In [1]:
import torch

In [5]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(t[0, :]) # 1행의 모든 열
print(t[:, 1]) # 모든행의 2번째 열
print(t[0, 1]) # 첫번째행의 2번째 열
print(t[0:2, 1:3]) # 첫번째와 두번째 행의 두번째와 세번째 열
c = t[t > 5]
d = t[t % 2 == 0]
print(c)
print(d)
print(t[[0,1],[1,2]])


tensor([1, 2, 3])
tensor([2, 5, 8])
tensor(2)
tensor([[2, 3],
        [5, 6]])
tensor([6, 7, 8, 9])
tensor([2, 4, 6, 8])
tensor([2, 6])


In [10]:
t = torch.rand(4,5)
x = t.view(5,4)
print(t)
z = t.view(10,-1)
print(z)

tensor([[0.2887, 0.0651, 0.5212, 0.2674, 0.9334],
        [0.5343, 0.8621, 0.7383, 0.7404, 0.3658],
        [0.2780, 0.1914, 0.5424, 0.0627, 0.0225],
        [0.5785, 0.9198, 0.3064, 0.0438, 0.9780]])
tensor([[0.2887, 0.0651],
        [0.5212, 0.2674],
        [0.9334, 0.5343],
        [0.8621, 0.7383],
        [0.7404, 0.3658],
        [0.2780, 0.1914],
        [0.5424, 0.0627],
        [0.0225, 0.5785],
        [0.9198, 0.3064],
        [0.0438, 0.9780]])


In [15]:
x = torch.rand(1)
print(x)
print(x.item())

y = torch.tensor(10)
print(y)
print(y.item())

tensor([0.5998])
0.5997721552848816
tensor(10)
10


In [17]:
x = torch.rand(1, 3, 3)
print(x)
print(x.shape)

y = torch.squeeze(x) # 크기 1인 차원이 축소 됨
print(y)
print(y.shape)

tensor([[[0.6544, 0.2206, 0.4257],
         [0.7566, 0.8783, 0.1335],
         [0.1229, 0.5240, 0.0131]]])
torch.Size([1, 3, 3])
tensor([[0.6544, 0.2206, 0.4257],
        [0.7566, 0.8783, 0.1335],
        [0.1229, 0.5240, 0.0131]])
torch.Size([3, 3])


In [27]:
x = torch.rand(3, 3, 3)
print(x)
print(x.shape)

y = torch.unsqueeze(x, dim=3) # dim 위치에 크기 1인 차원이 추가됨
print(y)
print(y.shape)

tensor([[[0.3441, 0.9591, 0.7979],
         [0.8366, 0.5264, 0.3164],
         [0.9943, 0.5793, 0.9502]],

        [[0.8292, 0.8088, 0.1324],
         [0.1635, 0.1066, 0.9487],
         [0.6958, 0.4275, 0.0737]],

        [[0.9817, 0.1961, 0.1573],
         [0.4236, 0.2081, 0.7952],
         [0.4132, 0.7129, 0.8527]]])
torch.Size([3, 3, 3])
tensor([[[[0.3441],
          [0.9591],
          [0.7979]],

         [[0.8366],
          [0.5264],
          [0.3164]],

         [[0.9943],
          [0.5793],
          [0.9502]]],


        [[[0.8292],
          [0.8088],
          [0.1324]],

         [[0.1635],
          [0.1066],
          [0.9487]],

         [[0.6958],
          [0.4275],
          [0.0737]]],


        [[[0.9817],
          [0.1961],
          [0.1573]],

         [[0.4236],
          [0.2081],
          [0.7952]],

         [[0.4132],
          [0.7129],
          [0.8527]]]])
torch.Size([3, 3, 3, 1])


In [30]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5,6], [7,8]])
c = torch.stack([a,b]) # 동일한 형식 텐서를 새롭게 그룹화 : 새로운 차원 생성
print(c)
print(c.ndim)
print(c.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3
torch.Size([2, 2, 2])


In [42]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5,6], [7,8]])
c = torch.cat((a,b), dim = 1) # dim = 결합 기준 축 0:행 1:열
print(c)
print(c.ndim)
print(c.shape)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
2
torch.Size([2, 4])


In [39]:
a = torch.rand(3,6)
print(a)

t1, t2, t3 = torch.chunk(a, 3, dim=1)
print(t1, t2, t3)

tensor([[0.6836, 0.2736, 0.4319, 0.6393, 0.5044, 0.5940],
        [0.9563, 0.7897, 0.2779, 0.8208, 0.5117, 0.3578],
        [0.1533, 0.6663, 0.3018, 0.9869, 0.1855, 0.5997]])
tensor([[0.6836, 0.2736],
        [0.9563, 0.7897],
        [0.1533, 0.6663]]) tensor([[0.4319, 0.6393],
        [0.2779, 0.8208],
        [0.3018, 0.9869]]) tensor([[0.5044, 0.5940],
        [0.5117, 0.3578],
        [0.1855, 0.5997]])


In [51]:
x = torch.tensor([1, 2, 3, 4, 5, 6])

result_x = torch.split(x, split_size_or_sections=2, dim=0)
print(result_x)

y = torch.tensor([1, 2, 3, 4, 5])

result_y = torch.split(y, split_size_or_sections=[1, 1, 3], dim=0)
print(result_y)

(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))
(tensor([1]), tensor([2]), tensor([3, 4, 5]))
