## PyTorch Quiz 2 : 연산

In [1]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [3]:
# 여기에 코드를 작성합니다
x = torch.tensor([2,4,6])
y = x + 5
print(y)
z = x - 3
print(z)


tensor([ 7,  9, 11])
tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [5]:
# 여기에 코드를 작성합니다
x = torch.randn(3,3)
y = torch.randn(3,3)

add = torch.add(x,y)
print(add)
sub = torch.sub(x,y)
print(sub)
mul = torch.mul(x,y)
print(mul)
div = torch.div(x,y)
print(div)

tensor([[-1.8134,  1.2424, -1.8656],
        [-2.9867, -2.1216,  0.2866],
        [-3.1650,  1.7353, -0.1902]])
tensor([[ 0.2088, -0.3534, -0.4361],
        [ 1.2441,  0.2056,  0.6994],
        [-2.6723,  2.4862, -0.0289]])
tensor([[ 0.8112,  0.3547,  0.8225],
        [ 1.8431,  1.1147, -0.1017],
        [ 0.7190, -0.7925,  0.0088]])
tensor([[ 0.7935,  0.5571,  1.6102],
        [ 0.4119,  0.8233, -2.3884],
        [11.8470, -5.6215,  1.3587]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [7]:
# 여기에 코드를 작성합니다
a = torch.tensor([[1,2,3], [4,5,6]])
b = torch.tensor([[7,8],[9,10],[11,12]])

result = torch.matmul(a,b)
print(result)

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [12]:
# 여기에 코드를 작성합니다
r1 = result + 10
print(r1)
r2 = torch.clamp(r1, max=100)
print(r2)

tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [15]:
# 여기에 코드를 작성합니다
m = torch.tensor([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

m1 = torch.sum(m, dim = 0)
print(m1)

tensor([55, 60, 65, 70, 75])
